name: CI Pipeline

# WHEN will start: on push in any branch and PR 
on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest # ON WHICH OC should this be run

    steps:
      # step-1: Download the rep code to VirtualM.
      - name: Checkout code
        uses: actions/checkout@v4

      # step-2: Check that python code is valid (simple test)
      - name: Check Python syntax
        run: python3 -m py_compile app.py

      # step-3: Build Docker-image 
      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      # step-4: Start container and check that it work
      - name: Test container runs
        run: docker run --rm myapp:${{ github.sha  }}
